### ISSUE TITLE
ADD getmarkethistory

### ISSUE THREAD

**Issue by yordis** [straw-hat-llc/elixir_bittrex#9]
- [x]  What is the differences between `Quantity` and `Total`?

**Comment by saniales** [comment]
1. the context
2. example to reproduce the call
3. question 

so far only 3. is satisfied :D

**Comment by saniales** [comment]
if you refer to `GET getmarkethistory?marketName=.......` call:
`quantity` is the quantity of coins purchased or sold in the order
`total` is `quantity * price`
